update github status to allow for drier object oriented usage
Invoca/jenkins-pipeline pull request #7
Opened 2018-07-09 23:30 UTC by jebentier

Doing this to help with dryness in pipeline files that are looking to set many statuses for the same sha

2018-07-10 15:49 UTC, jadametz reviewed
Can you provide a brief example of what calling this in a pipeline would look like?

2018-07-10 16:49 UTC, jebentier commented
Yes, example new usage is
```
githubStatusChecks = new GitHubStatus(this, 'Invoca/web', env.GIT_SHA,  env.BUILD_URL, env.TOKEN)
githubStatusChecks.setStatus('jenkins-ci/production-assets-pushed', 'Assets pushed to s3://invoca-assets', 'success')
```
or you can still use the old
```
gitHubStatus([
    repoSlug:    'Invoca/web',
    sha:         env.GIT_COMMIT,
    description: 'Assets pushed to s3://invoca-assets',
    context:     'jenkins-ci/production-assets-pushed',
    targetURL:   env.BUILD_URL,
    token:       env.GITHUB_TOKEN,
    status:      'success'
])
```

2018-07-10 16:55 UTC, jebentier commented
Yes, example new usage is
```
githubStatusChecks = new GitHubStatus(this, '<repo>', env.GIT_SHA,  env.BUILD_URL, env.TOKEN)
githubStatusChecks.setStatus('jenkins-ci/production-assets-pushed', 'Assets pushed to S3', 'success')
```
or you can still use the old
```
gitHubStatus([
    repoSlug:    '<repo>',
    sha:         env.GIT_COMMIT,
    description: 'Assets pushed to S3',
    context:     'jenkins-ci/production-assets-pushed',
    targetURL:   env.BUILD_URL,
    token:       env.GITHUB_TOKEN,
    status:      'success'
])
```

2018-07-10 17:05 UTC, jadametz approved these changes

2018-07-10 18:26 UTC, jebentier commented
is there a contrib anywhere on how to apply contributions and make them public?

2018-07-10 18:27 UTC, cmparkinson requested changes

2018-07-10 18:27 UTC, cmparkinson commented on src/com/invoca/github/GitHubStatus.groovy
> +  public void setStatus(String context, String status, String description) {
`GitHubStatus` objects are meant to encapsulate an individual status.  `context` is part of the composite key that identifies each status, so it should be included in the constructor.

Nit: `public` is the default in Groovy.

2018-07-10 20:12 UTC, jebentier commented
@cmparkinson after an offline talk i went ahead and extracted the github api portion out into it's own object, which allows for things to be dried up.  I also switched the instance method `update` to take the new status as apposed to having the status be a part of the `GitHubStatus` object.  This feel like a better contract given our discussion about the idea of getting the current status from the API.

original execution of gitHubStatus variable remains working, and drier usage of GitHubStatus looks like:
```
github_status = new GitHubStatus([
    repoSlug:    '<repo>',
    sha:         env.GIT_COMMIT,
    description: 'Assets pushed to S3',
    context:     'jenkins-ci/production-assets-pushed',
    targetURL:   env.BUILD_URL,
    token:       env.GITHUB_TOKEN
])

github_status.update('success')
github_status.update('failure')
```

2018-07-19 19:35 UTC, cmparkinson approved these changes

2018-07-19 20:22 UTC, jebentier commented
@cmparkinson @jadametz am i good to merge this? and what's the release process?

2018-07-19 23:08 UTC, jadametz commented
Looks good to merge. No formally outlined contribution guidelines at the moment. To make it available it just needs to have a tag/release. Feel free to add release notes 😄

2018-07-20 20:17 UTC, merged